### ISSUE TITLE
SynchronizedTojos

### ISSUE THREAD

**Issue by yegor256** [yegor256/tojos#16]
Let's create a decorator for `Tojos`, which will ensure that all manipulations are thread-safe.

**Comment by l3r8yJ** [comment]
@yegor256 can you please tell me if the changes I made are similar to what you need? This is not the final version, unit tests are required.

**Comment by yegor256** [comment]
@l3r8yJ please, submit a pull request, I will be able to review it

**Comment by l3r8yJ** [comment]
@yegor256 sure!

**Comment by l3r8yJ** [comment]
@yegor256 should I leave syncronized for the entire method or separate it out into a separate block as qulice's pmd advises?
```
[INFO] PMD: src/main/java/com/yegor256/tojos/SynchronizedTojos.java[63-73]: Use block level rather than method level synchronization (AvoidSynchronizedAtMethodLevel)
```

**Comment by yegor256** [comment]
@l3r8yJ PMD is right. Making entire methods `synchronized` is a bad practice. I suggest, for this task, to follow this workflow: https://www.yegor256.com/2022/08/04/code-and-tests-different-pull-requests.html Make a test first, make sure it fails, annotate it with `@Disabled`. Prove that current implementation of Tojos is not thread-safe. Commit and push and merge. Then, create `SynchronizedTojos` and make the test pass.

**Comment by l3r8yJ** [comment]
@yegor256 i saw that synctojo was implemented inside eo, is this issue relevant? and is it worth moving the implementation from eo to tojos?

**Comment by yegor256** [comment]
@l3r8yJ of course, we need it here, not in EO

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.0`

**Comment by yegor256** [comment]
@mximp FYI
