### ISSUE TITLE
replacement and removal of tojos

### ISSUE THREAD

**Issue by OlesiaSub** [yegor256/tojos#32]
@yegor256 how can I replace or remove tojos from catalog?
As far as I understood, method `set` adds a new tojo, but what if I want to replace some attributes of the tojo?

**Comment by yegor256** [comment]
@OlesiaSub there is no way to do this now. You are welcome to make a pull request!

**Comment by OlesiaSub** [comment]
@yegor256 Just to be clear, if I use method `set` on an object with `id=1` and there already is an object with the same `id` in the catalog (I just want to change some attributes) - will a new object be created in the catalog or will the existing object's attributes be replaced?

**Comment by yegor256** [comment]
@OlesiaSub see c551b91

**Comment by yegor256** [comment]
@OlesiaSub I'm closing this. if any additional questions, please open a new ticket
