### ISSUE TITLE
Thread safe Mono

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/tojos#39]
During solving the eo [issue](https://github.com/objectionary/eo/issues/1337) we faced with the concurrency problem. The problem in `MnCsv` - it's not a thread safe class. I suggest to implement something like `ThreadSafeMono` which will make `read/write` locks for both methods. In other words, we need a thread safe implementation of `Mono` as a decorator for other `Mono` classes.

**Comment by l3r8yJ** [comment]
@yegor256 can i help you here?

**Comment by yegor256** [comment]
@l3r8yJ sure, go ahead. Would be nice to have `MnSynchronized` decorator of `Mono`, I believe

**Comment by volodya-lombrozo** [comment]
@l3r8yJ I think it makes sense.  Otherwise you can `read()` some garbadge  if another thread will be in the middle of the `write()`, in some cases you can get even an exception. The actuall behaviour will depend on decorated object.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo got u

**Comment by yegor256** [comment]
@rultor release, tag is `0.15.0`

**Comment by yegor256** [comment]
@volodya-lombrozo should be fixed in 0.15.0

**Comment by yegor256** [comment]
@volodya-lombrozo should I release a new version here?
