### ISSUE TITLE
Concurrent perfomance in TjSynchronized

### ISSUE THREAD

**Issue by l3r8yJ** [yegor256/tojos#43]
I suggest using `ReetreentReadWriteLock` instead of `synchronized(this.wrapped)` in `TjSynchronized`, or is this unnecessary as long as we don't have performance problems? @yegor256 what do you think?

**Comment by l3r8yJ** [comment]
I'll take it

**Comment by yegor256** [comment]
@l3r8yJ sure, go ahead
