### ISSUE TITLE
We need `SynchronizedTojo` or synchronisation in `MonoTojo`

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/tojos#46]
Now we have two classes that have synchronised implementations:
1. `TjSynchronized`
2. `MnSynchronized`

Both of them have their own place, but we also need `SynchronizedTojo`. Why? Because each `Tojo` knows how to work with `Mono` and how to save its own fields using `Mono`. In other words, `Tojo` has the next logic (schematically):
```java
class Tojo {
  Mono mono;
  void save() {
    map = mono.read();
    map.add(something);
    mono.save(map)
  }
}
```
As you can see - it's not a thread safe code at all, even if `Mono` itself is a thread safe. It means we need a `Tojo` that will be synchronized on `Mono`. We need `SynchronizedTojo`. The same that was suggested [here](https://github.com/objectionary/eo/issues/1337). Or we can synchronise access in `MonoTojo`

**Comment by volodya-lombrozo** [comment]
@yegor256 assign to me, I need to solve it fast.

**Comment by yegor256** [comment]
@volodya-lombrozo go ahead
