### ISSUE TITLE
Reading from `MonoTojo` not efficient

### ISSUE THREAD

**Issue by volodya-lombrozo** [yegor256/tojos#60]
Not so long ago, we encountered a problem with frequent reading from `MonoTojo` while filtering around 1000 rows.

The code looks like this:
```java
final Collection<Tojo> before = this.tojos.value().select(
         row -> row.get(Tojos.KEY).equals("some-id") && "class".equals(row.get("kind"))
);
```
This statement takes a lot of time to read, around 15-30 ms. When we have around 1000 iterations, it takes a total of 1.5-3 seconds to execute, which is unacceptable.

`tojos` is created like this:
```java
return new TjCached(new TjDefault(new MnPostponed(new MnCsv(path), 500L)));
```

The original issue: https://github.com/objectionary/eo/issues/1894

**Comment by yegor256** [comment]
@volodya-lombrozo do you know how to fix this?

**Comment by volodya-lombrozo** [comment]
@yegor256 Not yet, but I can invent something if you will assign the issue to me

**Comment by yegor256** [comment]
@volodya-lombrozo you have it, but be careful - this may require a massive redesign of the entire library. We don't want this, without a detailed analysis of the situation. So, if you can introduce a cheap/quick fix, great. If not, don't spend too much time.
